spring:
  application:
    name: GATEWAY-SERVICE
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 100MB
  webflux:
    multipart:
      max-in-memory-size: 100MB
      max-disk-usage-per-part: 100MB
      max-parts: 1
#  profiles:
#    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/oauth2/**, /api/v1/auth/**, /api/v1/users/**, /api/v1/address/**
          filters:
            - RewritePath=/api/oauth2/(?<segment>.*), /oauth2/${segment}
            - RewritePath=/api/v1/auth/signup, /signup
            - RewritePath=/api/v1/auth/register, /register
            - RewritePath=/api/v1/users, /users
            - RewritePath=/api/v1/address, /address
        - id: NOTI-SERVICE
          uri: lb://NOTI-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181


server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.springframework.web: DEBUG
    org.springframework.security: trace
    web: trace
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
