spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # tự động định tuyến dựa vào serviceId
          lower-case-service-id: true # chuyển đổi serviceId thành chữ thường
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AddRequestHeader=X-API-KEY, ${gateway.x-api-key}
            - RewritePath=/api/v1/auth/signup, /signup
            - RewritePath=/api/v1/auth/login, /login
            - RewritePath=/api/v1/auth/register, /register
            - RewritePath=/api/v1/auth/refresh, /refresh
            - RewritePath=/api/v1/auth/send-verification-otp, /send-verification-otp
            - RewritePath=/api/v1/auth/users, /users
            - RewritePath=/api/v1/auth/roles, /roles
            - RewritePath=/api/v1/auth/permissions, /permissions
        - id: NOTI-SERVICE
          uri: lb://NOTI-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
  data:
    redis:
      host: localhost
      port: 6379
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181
jwt:
  secret: 4f9c1f5e70ee039c9f6fab00b56531e8c0e97b207f96c2bcc7177a7cba528a138a02985e1c10f73c7220e133351a19f8e6f242fd155ebc08c5c9ac7693d5007d
gateway:
  x-api-key: api-key


server:
  port: 8080

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.springframework.web: DEBUG
    org.springframework.security: trace
    web: trace

