spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: eMartix
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: localhost
    port: 5672
    username: eMartix
    password: 12345

  application:
    name: ORDER-SERVICE

server:
  port: 8083

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web: DEBUG
