spring:
  boot:
    message: 'product-service'
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: eMartix
    password: 12345
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: eMartix
    password: 12345



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

logging:
  level:
    web: trace
    org.springframework.security: trace
server:
  port: 8082
springdoc:
  swagger-ui:
    path: /swagger-ui