spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    web: trace
    org.springframework.security: trace

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
